{{- if gt (len .Values.auth.users) 0 }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "ingress-auth.fullname" . }}
  namespace: {{ include "ingress-auth.namespace" . }}
  labels:
    {{- include "ingress-auth.labels" . | nindent 4 }}
data:
  {{- range .Values.auth.users }}
  {{- if and .username .password }}
  {{ .username }}: {{ .password | b64enc }}
  {{- end }}
  {{- end }}
{{- end }}


{{- if .Values.auth.caCrt }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ default (printf "%s-ca" (include "ingress-auth.fullname" .)) .Values.auth.secretName }}
  namespace: {{ include "ingress-auth.namespace" . }}
  labels:
    {{- include "ingress-auth.labels" . | nindent 4 }}
data:
  ca.crt: {{ .Values.auth.caCrt | b64enc }}
{{- end }}
