{{- range $repo_key, $repo_value := .Values.configs.credentialTemplates }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $repo_key }}
  namespace: {{ $.Values.namespace }}
  labels:
    argocd.argoproj.io/secret-type: repository

stringData:
  {{- range $key, $value := $repo_value }}
  {{ $key }}: {{ $value | toString }}
  {{- end }}
{{- end }}
