{{- $root := . -}}
{{- if and $root.Values.imagePullSecret $root.Values.imagePullSecret.stringData }}
{{- range $nsName, $nsConfig := $root.Values.clientNamespaces }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $root.Values.imagePullSecret.name | quote }}
  namespace: {{ $nsName | quote }}
  labels:
    {{- include "client-namespaces.labels" $root | nindent 4 }}
type: {{ $root.Values.imagePullSecret.type | default "Opaque" }}
stringData:
  {{- toYaml $root.Values.imagePullSecret.stringData | nindent 2 }}
{{- end }}
{{- end }}