{{/* 
    this template aims at generating all the required service-accounts for the 'clients'
*/}}

{{- range $clientNamespaceName, $clientNamespaceValue := .Values.clientNamespaces }}
  {{/* let's not process system namespaces */}}
  {{- if not (or (hasPrefix "kube-" $clientNamespaceName) (eq $clientNamespaceName "default")) }}  
    {{/* for each 'rbac' item let's create a ServiceAccount if the subjectKind is "ServiceAccount" */}}
    {{- range $_, $rbacItem := (empty $clientNamespaceValue.rbac | ternary $.Values.defaults.rbac $clientNamespaceValue.rbac) }}
      {{- if eq $rbacItem.subjectKind "ServiceAccount" }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $rbacItem.subjectName }}
  namespace: {{ $clientNamespaceName }}
  labels:
    {{- include "client-namespaces.labels" $ | nindent 4 }}
  annotations:
    kubernetes.io/enforce-mountable-secrets: "false"

      {{- end }} {{/* if eq $rbacItem.subjectKind "ServiceAccount" */}}
    {{- end }} {{/* range $_, $rbacItem ... */}}
  {{- end }} {{/* if not (or ...) */}}
{{- end }} {{/* range $clientNamespaceName ...  */}}
