apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nubo-worker-scaler.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nubo-worker-scaler.labels" . | nindent 4 }}
data:
  EXCLUDED_CLUSTER_SUBSTRINGS: {{ join "," .Values.nubo.excludedClusterSubstrings | quote }}
  CAPI_API_VERSION: {{ .Values.nubo.capiMachineApiVersion | quote }}
  FALLBACK_REPLICAS: {{ .Values.nubo.fallbackReplicas | quote }}
  POLL_INTERVAL_SECONDS: {{ .Values.nubo.pollIntervalSeconds | quote }}
  POLL_TIMEOUT_SECONDS: {{ .Values.nubo.pollTimeoutSeconds | quote }}
  NO_WAIT: {{ .Values.nubo.noWait | quote }}
  DRY_RUN: {{ .Values.dryRun | quote }}
