{{- if or .Values.extraFiles .Values.extraFilesTemplate }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "autofix.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "autofix.labels" . | nindent 4 }}
  annotations:
    {{- include "autofix.hookAnnotations" . | nindent 4 }}
data:
  {{- if .Values.extraFiles }}
  {{- toYaml .Values.extraFiles | nindent 2 }}
  {{- end }}
  {{- if .Values.extraFilesTemplate }}
  {{- tpl (toYaml .Values.extraFilesTemplate | nindent 2) . }}
  {{- end }}
{{- end }}
