apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: auditbeat
  namespace: {{ .Release.Namespace }}
  labels:
    k8s-app: auditbeat
rules:
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs: ["get", "create", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: auditbeat-kubeadm-config
  namespace: {{ .Release.Namespace }}
  labels:
    k8s-app: auditbeat
rules:
  - apiGroups: [""]
    resources:
      - configmaps
    resourceNames:
      - kubeadm-config
    verbs: ["get"]