apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pgbench-job.fullname" . }}-scripts
  labels:
    {{- include "pgbench-job.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
data:
  prepare_pgbench.sh: {{ tpl (.Files.Get "scripts/prepare_pgbench.sh") . | quote }}
  run_pgbench_tests.sh: {{ tpl (.Files.Get "scripts/run_pgbench_tests.sh") . | quote }}
  run_benchmark.sh: {{ tpl (.Files.Get "scripts/run_benchmark.sh") . | quote }}
