apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}-fio-deployment
  labels:
    app: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  restartPolicy: Never
  securityContext:
    {{- toYaml .Values.podSecurityContextFio | nindent 6 }}

  containers:
  - name: fio
    image: xridge/fio
    command:
      - /bin/sh
      - -c

    args:
      - |
        echo "Container started";
        while true; do
        sleep 3600;
        done
    volumeMounts:
      - name: scripts
        mountPath: /tmp/scripts
    resources:
      {{- toYaml .Values.resources | nindent 8 }}

    securityContext:
      {{- toYaml .Values.securityContextFio | nindent 10 }}
  volumes:
  - name: scripts
    configMap:
      name: {{ .Release.Name }}-fio-scripts
      defaultMode: 0755