apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-fio-scripts
  labels:
    app: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
data:
  launch_fio.sh: {{ tpl (.Files.Get "scripts/launch_fio.sh") . | quote }}