{{- if not .Values.postgres.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pgbench-job.fullname" . }}-postgres
  labels:
    {{- include "pgbench-job.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  password: {{ .Values.postgres.password | quote }}
{{- end }}
