{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "pgbench-job.serviceAccountName" . }}
  labels:
    {{- include "pgbench-job.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
{{- end }}
