{{- range $nameSuffix, $values := .Values.externalsecrets }}
{{- if or (and (hasKey $values "dataFrom") (hasKey $values "template")) (and (not (hasKey $values "dataFrom")) (not (hasKey $values "template"))) }}
{{- fail "Secret must have either dataFrom or template key." }}
{{- end }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ $values.name }}
  namespace: {{ default "default" $values.namespace }}
  {{- if $values.annotations }}
  annotations:
    {{- toYaml $values.annotations | nindent 4 }}
  {{- end }}
spec:
  refreshInterval: {{ default "1h0m0s" $values.refreshInterval }}
  secretStoreRef:
    kind: {{ default "ClusterSecretStore" $values.secretStoreKind }}
    name: {{ default "openbao-ppr" $values.secretStoreName }}
  target:
    creationPolicy: {{ default "Owner" $values.creationPolicy }}
    deletionPolicy: Retain
    name: {{ $values.name }}
    {{- if or (hasKey $values "template") $values.labels $values.annotations }}
    template:
      {{- if hasKey $values "template" }}
      data: {{ toYaml $values.template | nindent 8 }}
      engineVersion: v2
      mergePolicy: Replace
      {{- end }}
      {{- if or $values.annotations $values.labels }}
      metadata:
        {{- with $values.annotations }}
        annotations:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with $values.labels }}
        labels:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      {{- end }}
      {{- if hasKey $values "template" }}
      type: {{ default "Opaque" $values.type }}
      {{- end }}
    {{- end }}
    {{- if hasKey $values "template" }}
  data:
    {{- range $i, $v := $values.secrets }}
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: {{ $v.key }}
        metadataPolicy: None
        property: {{ $v.property }}
      secretKey: {{ $v.property }}
    {{- end }}
    {{- end }}
  {{- if hasKey $values "dataFrom" }}
  dataFrom: {{ toYaml $values.dataFrom | nindent 4 }}
  {{- end }}
{{- end -}}
