{{- if not .Values.secret.useExistingSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $repo_key }}
  namespace: {{ .Values.namespace }}
stringData:
  ACCESS_KEY_ID: {{ .Values.secret.ACCESS_KEY_ID }}
  ACCESS_SECRET_KEY: {{ .Values.secret.ACCESS_SECRET_KEY }}
{{- end }}
