apiVersion: v1
kind: Secret
metadata:
  name: web-scanner-ssh-authorized-keys
  namespace: {{ .Release.Namespace | quote }}
type: Opaque
stringData:
  authorized_keys: {{ .Values.web_scanner_ssh_authorized_keys }}
---
apiVersion: v1
kind: Secret
metadata:
  name: ssh-private-key
  namespace: {{ .Release.Namespace | quote }}
type: Opaque
stringData:
  id_ed25519: |
{{ .Values.ssh_private_key | nindent 4 }}
