---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "minio-backup.name" . }}
  namespace: {{ .Release.Namespace }}
stringData:
  MC_HOST_{{ .Values.minio.tenantName }}: "https://{{ .Values.minio.user }}:{{ .Values.minio.pass }}@minio.{{ .Values.minio.namespace }}.svc"
  AWS_ACCESS_KEY_ID: "{{ .Values.restic.accessKey }}"
  AWS_SECRET_ACCESS_KEY: "{{ .Values.restic.secretAccessKey }}"
  RESTIC_REPOSITORY: "{{ .Values.restic.repository }}"
  RESTIC_PASSWORD: "{{ .Values.restic.repositoryPassword }}"
