annotations: {}
externalSecretsNamespace: "external-secrets"
releaseName: ""
# ── Secret identity ─────────────────────────────────────────────────────
vaultPath: ""    # relative path: VAULT_PATH_BASE/<vaultSubPath>

# ── Cluster role ────────────────────────────────────────────────────────
clusterRole: wapp

clusterName: ""
environment: "dev"
baoAddr: ""
secretStoreName: ""
forceRotatePassword: false
image: "ghcr.io/cloud-gouv/cluster-secret-provisioning-image:sha-f5495bd"
rbac:
  create: false
job:
  create: true

# ── PushSecret mappings (secretKey -> property in Bao) ─────────────────
pushMappings:
  # - secretKey: login
  #   property: login
  #   value: admin
  - secretKey: password
    property: password
    need_plain: false

# ── Generation script ───────────────────────
# use the encryption you need
generator:
  # Use $PLAIN_PASSWORD which is the plain password generated in script
  # Set true to use the command
  override: false
  command: argocd account bcrypt --password "$PLAIN_PASSWORD"
  # Use it for custome logic (eg: appRole)
  script: ""

extraEnvVars: {}
  # - name: TENANT_NAME
  #   value: xxx
