{{- range $repo_cred_key, $repo_cred_value := .Values.configs.externalSecrets }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-repo-creds-{{ $repo_cred_key }}
  namespace: {{ $.Values.namespace }}
spec:
  data:
  {{- range $i, $v := $repo_cred_value.secrets }}
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: {{ $v.key }}
      metadataPolicy: None
      property: {{ $v.property }}
    secretKey: {{ $v.property }}
  {{- end }}
  refreshInterval: {{ default "1h0m0s" $repo_cred_value.refreshInterval }}
  secretStoreRef:
    kind: {{ default "ClusterSecretStore" $repo_cred_value.secretStoreKind }}
    name: {{ default "openbao-ppr" $repo_cred_value.secretStoreName }}
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: argocd-repo-creds-{{ $repo_cred_key }}
    template:
      data:
      {{- range $i, $v := $repo_cred_value.secrets }}
        {{ $v.property }}: "{{ printf "{{ .%s }}" $v.property }}"
      {{- end }}
      engineVersion: v2
      mergePolicy: Replace
      metadata:
        {{- with $repo_cred_value.credentialTemplatesAnnotations }}
        annotations:
          {{- range $key, $value := . }}
          {{ $key }}: {{ $value | quote }}
          {{- end }}
        {{- end }}
        labels:
          argocd.argoproj.io/secret-type: repo-creds
      type: {{ default "Opaque" $repo_cred_value.type }}
{{- end -}}
