{{- range $repo_key, $repo_value := .Values.configs.repositories }}
---
apiVersion: v1
kind: Secret
metadata:
  name: argocd-repository-{{ $repo_key  | regexFind "[^/]*.git$" |trimSuffix ".git" }}
  namespace: {{ $.Values.namespace }}
  labels:
    argocd.argoproj.io/secret-type: repository
  {{- with $.Values.configs.repositoriesAnnotations }}
  annotations:
    {{- range $key, $value := . }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
stringData:
  {{- range $key, $value := $repo_value }}
  {{ $key }}: {{ $value | toString }}
  {{- end }}
{{- end }}
