{
 "title": "Coturn - Visio",
 "description": "CallCorp CoTURN",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "query0", "query": { "query": "label_values()" } }
  ]
 },
 "panels": [
  {
   "title": "Service availability",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"coturn\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Active allocations",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (instance) (turn_total_allocations{job=\"coturn\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Cumulative total traffic",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(turn_total_traffic_rcvp{job=\"coturn\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Relayed bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (instance) (rate(turn_total_traffic_rcvb{job=\"coturn\"}[$__rate_interval]))",
     "legendFormat": "RX - {{instance}}"
    },
    {
     "expr": "sum by (instance) (rate(turn_total_traffic_sentb{job=\"coturn\"}[$__rate_interval]))",
     "legendFormat": "TX - {{instance}}"
    },
    {
     "expr": "sum by (instance) (rate(turn_total_traffic_rcvb{job=\"coturn\"}[$__rate_interval]) + rate(turn_total_traffic_sentb{job=\"coturn\"}[$__rate_interval]))",
     "legendFormat": "Total RX/TX - {{instance}}"
    }
   ]
  },
  {
   "title": "Relayed packets per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (instance) (rate(turn_traffic_rcvp{job=\"coturn\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (instance) (rate(turn_traffic_sentp{job=\"coturn\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Packet drop rate (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (instance) (rate(turn_packet_dropped{job=\"coturn\"}[5m]))\n/\nclamp_min(\nsum by (instance) (\nrate(turn_packet_processed{job=\"coturn\"}[5m])\n+ rate(turn_packet_dropped{job=\"coturn\"}[5m])\n), 1\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}