{
 "title": "HAProxy",
 "description": "Test",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Source de données", "query": "prometheus" },
   {
    "name": "component_type",
    "label": "Type de composant",
    "query": {
     "query": "label_values({source=\"access\", appliance_type=\"$appliance_type\"},component_type)"
    }
   },
   { "name": "appliance_type", "label": "Type de machines", "query": "reverse_proxy" },
   {
    "name": "project_name",
    "label": "Nom du projet",
    "query": {
     "query": "label_values({source=\"access\", component_type=\"$component_type\", appliance_type=\"$appliance_type\"},project)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Backend Errors",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "increase(haproxy_backend_response_errors_total{appliance_type=\"$appliance_type\", component_type=\"$component_type\", project=\"$project_name\"}[$__rate_interval])",
     "legendFormat": "Backend Response Errors {{proxy}}"
    }
   ]
  },
  {
   "title": "Backend Sessions",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "haproxy_backend_max_sessions{appliance_type=\"$appliance_type\", component_type=\"$component_type\", project=\"$project_name\"}",
     "legendFormat": "{{__name__}} {{proxy}}"
    },
    {
     "expr": "haproxy_backend_limit_sessions{appliance_type=\"$appliance_type\", component_type=\"$component_type\", project=\"$project_name\"}",
     "legendFormat": "{{__name__}} {{proxy}}"
    }
   ]
  },
  {
   "title": "Frontend Problems",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "increase(haproxy_frontend_requests_denied_total{appliance_type=\"$appliance_type\", component_type=\"$component_type\", project=\"$project_name\"}[$__rate_interval])",
     "legendFormat": "Frontend Request Denied {{proxy}}"
    },
    {
     "expr": "increase(haproxy_frontend_request_errors_total{appliance_type=\"$appliance_type\", component_type=\"$component_type\", project=\"$project_name\"}[$__rate_interval])",
     "legendFormat": "Frontend Request Errors {{proxy}}"
    },
    {
     "expr": "increase(haproxy_frontend_denied_connections_total{component_type=\"$component_type\", appliance_type=\"$appliance_type\", project=\"$project_name\"}[$__rate_interval])",
     "legendFormat": "Frontend Denied Connections {{proxy}}"
    }
   ]
  },
  {
   "title": "Queue State",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "haproxy_backend_current_queue{component_type=\"$component_type\", appliance_type=\"$appliance_type\", project=\"$project_name\"}",
     "legendFormat": "{{__name__}} {{proxy}}"
    },
    {
     "expr": "haproxy_backend_max_queue{component_type=\"$component_type\", appliance_type=\"$appliance_type\", project=\"$project_name\"}",
     "legendFormat": "{{__name__}} {{proxy}}"
    }
   ]
  }
 ]
}