{
 "title": "Interco RIE - Visio - Coturn",
 "description": "CallCorp CoTURN",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Coturn active alocations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(sum by (instance) (turn_total_allocations{job=\"coturn\"}))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum by (instance) (turn_total_allocations{job=\"coturn\"}))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "type": "piechart",
   "gridPos": { "h": 11, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (osc_region) (label_replace(turn_total_allocations{job=\"coturn\"},\"osc_region\",\"cgw-$1\",\"instance\",\"^.*-(.*)\"))",
     "legendFormat": "{{osc_region}}"
    }
   ]
  },
  {
   "title": "Nb coturn with alloc > 0",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum by (instance) (turn_total_allocations{job=\"coturn\"}))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 19, "x": 2, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (instance) (turn_total_allocations{job=\"coturn\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Strongswan", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{Zone=\"high-traffic\",device=~\"ipsec-.*\"}[$__rate_interval])*8)",
     "legendFormat": "Usagers -> Livekits"
    },
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{Zone=\"high-traffic\",device=~\"ipsec-.*\"}[$__rate_interval])*8)",
     "legendFormat": "Livekits -> Usagers"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_packets_total{Zone=\"high-traffic\",device=~\"ipsec-.*\"}[$__rate_interval]))",
     "legendFormat": "Usagers -> Livekits"
    },
    {
     "expr": "sum(rate(node_network_transmit_packets_total{Zone=\"high-traffic\",device=~\"ipsec-.*\"}[$__rate_interval]))",
     "legendFormat": "Livekits -> Usagers"
    }
   ]
  },
  {
   "title": "Trafic total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{Zone=\"high-traffic\",device=~\"ipsec-.*\"}[$__rate_interval])*8)",
     "legendFormat": "Rx ipsec (usagers → livekits)"
    },
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{Zone=\"high-traffic\",device=~\"ipsec-.*\"}[$__rate_interval])*8)",
     "legendFormat": "Tx ipsec (livekits → usagers)"
    }
   ]
  },
  {
   "title": "PPS Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_packets_total{Zone=\"high-traffic\",device=~\"ipsec-.*\"}[$__rate_interval]))",
     "legendFormat": "Rx ipsec (usagers → livekits)"
    },
    {
     "expr": "sum(rate(node_network_transmit_packets_total{Zone=\"high-traffic\",device=~\"ipsec-.*\"}[$__rate_interval]))",
     "legendFormat": "Tx ipsec (livekits → usagers)"
    }
   ]
  },
  {
   "title": "Répartition par BOX RIE",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum by (device) (rate(node_network_transmit_bytes_total{Zone=\"high-traffic\",device=~\"ipsec-.*\"}[$__rate_interval]) * 8)",
     "legendFormat": "Tx {{device}}"
    },
    {
     "expr": "sum by (device) (rate(node_network_receive_bytes_total{Zone=\"high-traffic\",device=~\"ipsec-.*\"}[$__rate_interval]) * 8)",
     "legendFormat": "Rx {{device}}"
    }
   ]
  },
  {
   "title": "Répartition des PPS par VPC",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum by (vpc_number) (label_replace(rate(node_network_receive_packets_total{Zone=\"high-traffic\",device=~\"ipsec-.*\"}[$__rate_interval]),\"vpc_number\",\"$1\",\"instance\",\"^.*-(.*)-(.*)\"))",
     "legendFormat": "Rx ipsec vpc{{vpc_number}}"
    },
    {
     "expr": "sum by (vpc_number) (label_replace(rate(node_network_transmit_packets_total{Zone=\"high-traffic\",device=~\"ipsec-.*\"}[$__rate_interval]),\"vpc_number\",\"$1\",\"instance\",\"^.*-(.*)-(.*)\"))",
     "legendFormat": "Tx ipsec vpc{{vpc_number}}"
    }
   ]
  },
  {
   "title": "Repartition par sous-région OSC",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum by (region) (label_replace(rate(node_network_transmit_bytes_total{Zone=\"high-traffic\",device=~\"ipsec-.*\"}[$__rate_interval]) * 8,\"region\",\"cgw-$1\",\"instance\",\"^.*-(.*)\"))",
     "legendFormat": "Tx ipsec ({{region}})"
    },
    {
     "expr": "sum by (region) (label_replace(rate(node_network_receive_bytes_total{Zone=\"high-traffic\",device=~\"ipsec-.*\"}[$__rate_interval]) * 8,\"region\",\"cgw-$1\",\"instance\",\"^.*-(.*)\"))",
     "legendFormat": "Rx ipsec ({{region}})"
    }
   ]
  },
  {
   "title": "Packets error rate seen by kernel",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_errs_total{Zone=\"high-traffic\"}[$__rate_interval])",
     "legendFormat": "Rx {{instance}}.{{device}}"
    },
    {
     "expr": "rate(node_network_transmit_errs_total{Zone=\"high-traffic\"}[$__rate_interval])",
     "legendFormat": "Tx {{instance}}.{{device}}"
    }
   ]
  },
  { "title": "Coturn", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Relayed  bandwidth per second seen by coturn",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (instance) (rate(turn_total_traffic_rcvb{job=\"coturn\"}[$__rate_interval]))",
     "legendFormat": "RX - {{instance}}"
    },
    {
     "expr": "sum by (instance) (rate(turn_total_traffic_sentb{job=\"coturn\"}[$__rate_interval]))",
     "legendFormat": "TX - {{instance}}"
    },
    {
     "expr": "sum by (instance) (rate(turn_total_traffic_rcvb{job=\"coturn\"}[$__rate_interval]) + rate(turn_total_traffic_sentb{job=\"coturn\"}[$__rate_interval]))",
     "legendFormat": "Total RX/TX - {{instance}}"
    }
   ]
  },
  {
   "title": "Relayed packets per second seen by coturn",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (instance) (rate(turn_traffic_rcvp{job=\"coturn\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (instance) (rate(turn_traffic_sentp{job=\"coturn\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Availability / health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "Nb VPC avec PPS > 0",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 52 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (\n  (sum by (instance) (rate(node_network_receive_packets_total{Zone=\"high-traffic\",device=~\"ipsec-.*\"}[10m]) + rate(node_network_transmit_packets_total{Zone=\"high-traffic\",device=~\"ipsec-.*\"}[10m]))) > 0\n)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Limite de PPS par VPC Outscale",
   "type": "stat",
   "gridPos": { "h": 5, "w": 22, "x": 2, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (instance) (rate(node_network_receive_packets_total{Zone=\"high-traffic\",device=~\"ipsec-.*\"}[$__rate_interval]) + rate(node_network_transmit_packets_total{Zone=\"high-traffic\",device=~\"ipsec-.*\"}[$__rate_interval])) * 2",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Failing Strongswan ",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 57 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_systemd_unit_state{name=\"strongswan.service\",Role=\"strongswan\",source=\"access\",Zone=\"high-traffic\",state=\"failed\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Failing Coturn ",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 57 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (instance) (node_systemd_unit_state{name=\"coturn.service\",Role=\"coturn-visio\",source=\"access\",Zone=\"high-traffic\",state=\"failed\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Node pressure CPU waiting - VM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(node_pressure_cpu_waiting_seconds_total{Zone=\"high-traffic\"}[$__rate_interval]) )by(Name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failing cloud-init",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 64 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_systemd_unit_state{name=\"cloud-final.service\",source=\"access\",Zone=\"high-traffic\",state=\"failed\"}",
     "legendFormat": "{{Name}}"
    }
   ]
  },
  {
   "title": "Max node pressure CPU waiting - Role",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max by (Role) (rate(node_pressure_cpu_waiting_seconds_total{Zone=\"high-traffic\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Packet drop rate (%) seen by coturn",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (instance) (rate(turn_packet_dropped{job=\"coturn\"}[5m]))\n/\nclamp_min(\nsum by (instance) (\nrate(turn_packet_processed{job=\"coturn\"}[5m])\n+ rate(turn_packet_dropped{job=\"coturn\"}[5m])\n), 1\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "(wip] Nombre d'allocations par bénéficiaire",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(beneficiary) (\n    count_over_time(\n        {service_name=\"coturn.service\"}\n        |= \"remote \"\n        | regexp \"remote (?P<user_ip>([0-9]+[.]){3}[0-9]+)\"\n        | user_ip != ip(\"100.64.16.0/24\") != ip(\"100.64.0.0/20\")\n        | label_format beneficiary=\"Autres\"\n        [$__auto]\n    )\n) ",
     "legendFormat": "{{beneficiary}}"
    }
   ]
  }
 ]
}