{
 "title": "Chaines d'accès bénéficiaires",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "project",
    "query": {
     "query": "label_values({source=\"access\"},project)"
    }
   },
   {
    "name": "component_type",
    "query": {
     "query": "label_values({source=\"access\"},component_type)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Publication \"${project}\"",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "project"
  },
  {
   "title": "HAProxy chaine d'accès (frontend reqs/s)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "delta(haproxy_frontend_connections_total{source=\"access\",appliance_type=\"reverse_proxy\",component_type=\"${component_type}\",proxy=\"443-tcp\",project=\"${project}\"}[2m]) / 120",
     "legendFormat": "Requêtes par secondes (port 443) ({{ availability_zone }})"
    }
   ]
  },
  {
   "title": "HAProxy Chaine d'accès (sessions courantes backend)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "haproxy_backend_current_sessions{source=\"access\",appliance_type=\"reverse_proxy\",component_type=\"${component_type}\",project=\"${project}\",proxy=\"cluster_k8s_workload_1:443\"}",
     "legendFormat": "Sessions"
    }
   ]
  },
  {
   "title": "Trafic sur les firewall de la chaine d'accès ",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "delta(node_network_receive_bytes_total{source=\"access\", component_type=\"${component_type}\", appliance_type=\"firewall\", project=\"${project}\",device=~\"^(?:pub_in|pub_out|admin)$\"}[2m]) / 120 * 8 / 1024",
     "legendFormat": "RX {{device}} ({{ availability_zone }}) (avg over 2m)"
    },
    {
     "expr": "-delta(node_network_transmit_bytes_total{source=\"access\", component_type=\"${component_type}\", appliance_type=\"firewall\", project=\"${project}\",device=~\"^(?:pub_in|pub_out|admin)$\"}[2m]) / 120 * 8 / 1024",
     "legendFormat": "TX {{device}} ({{ availability_zone }}) (avg over 2m)"
    },
    {
     "expr": "delta(node_network_receive_bytes_total{source=\"access\", component_type=\"${component_type}\", appliance_type=\"firewall\", project=\"${project}\",device=~\"^(?:pub_in|pub_out|admin)$\"}[1h]) / 3600 * 8 / 1024",
     "legendFormat": "Average RX {{ device }} {{ availability_zone }} over 1h"
    },
    {
     "expr": "delta(node_network_receive_bytes_total{source=\"access\", component_type=\"${component_type}\", appliance_type=\"firewall\", project=\"${project}\",device=~\"^(?:pub_in|pub_out|admin)$\"}[1h] offset 7d) / 3600 * 8 / 1024",
     "legendFormat": "Average RX {{ device }} {{ availability_zone }} over 1h (last week)"
    },
    {
     "expr": "-delta(node_network_transmit_bytes_total{source=\"access\", component_type=\"${component_type}\", appliance_type=\"firewall\", project=\"${project}\",device=~\"^(?:pub_in|pub_out|admin)$\"}[1h]) / 3600 * 8 / 1024",
     "legendFormat": "Average TX {{ device }} {{ availability_zone }} over 1h"
    },
    {
     "expr": "-delta(node_network_transmit_bytes_total{source=\"access\", component_type=\"${component_type}\", appliance_type=\"firewall\", project=\"${project}\",device=~\"^(?:pub_in|pub_out|admin)$\"}[1h] offset 7d) / 3600 * 8 / 1024",
     "legendFormat": "Average TX {{ device }} {{ availability_zone }} over 1h (last week)"
    }
   ]
  },
  {
   "title": "Paquets sur les firewall de la chaine d'accès",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 22 },
   "repeat": "interface_in",
   "targets": [
    {
     "expr": "delta(node_network_receive_packets_total{source=\"access\",appliance_type=\"firewall\",component_type=\"${component_type}\",device=~\"^(?:pub_in|pub_out|admin)$\",project=\"${project}\"}[2m]) / 120",
     "legendFormat": "RX {{device}} ({{ availability_zone }})"
    },
    {
     "expr": "-delta(node_network_transmit_packets_total{source=\"access\",appliance_type=\"firewall\",component_type=\"${component_type}\",device=~\"^(?:pub_in|pub_out|admin)$\",project=\"${project}\"}[2m]) / 120",
     "legendFormat": "TX {{device}} ({{ availability_zone }})"
    }
   ]
  },
  {
   "title": "DNS Probe Check",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (source, component_type, job) (probe_success{source=\"access\",component_type=\"${component_type}\",job=\"integrations/blackbox/dns\",project=\"${project}\"}) * 100",
     "legendFormat": "Successful DNS queries"
    },
    {
     "expr": "(1 - avg by (source, component_type, job) (probe_success{source=\"access\",component_type=\"${component_type}\",job=\"integrations/blackbox/dns\",project=\"${project}\"})) * 100",
     "legendFormat": "Failed DNS queries"
    }
   ]
  },
  {
   "title": "ICMP Probe Check",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (source, component_type, job) (probe_success{source=\"access\",component_type=\"${component_type}\",job=\"integrations/blackbox/icmp\",project=\"${project}\"}) * 100",
     "legendFormat": "Successful ICMP queries"
    },
    {
     "expr": "(1 - avg by (source, component_type, job) (probe_success{source=\"access\",component_type=\"${component_type}\",job=\"integrations/blackbox/icmp\",project=\"${project}\"})) * 100",
     "legendFormat": "Failed ICMP queries"
    }
   ]
  },
  {
   "title": "HTTP Probe Check",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (source, component_type, job) (probe_success{source=\"access\",component_type=\"${component_type}\",job=\"integrations/blackbox/http\",project=\"${project}\"}) * 100",
     "legendFormat": "Successful HTTP queries"
    },
    {
     "expr": "(1 - avg by (source, component_type, job) (probe_success{source=\"access\",component_type=\"${component_type}\",job=\"integrations/blackbox/http\",project=\"${project}\"})) * 100",
     "legendFormat": "Failed HTTP queries"
    }
   ]
  },
  {
   "title": "TCP Probe Check",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (source, component_type, job) (probe_success{source=\"access\",component_type=\"${component_type}\",job=\"integrations/blackbox/tcp\",project=\"${project}\"}) * 100",
     "legendFormat": "Successful TCP queries"
    },
    {
     "expr": "(1 - avg by (source, component_type, job) (probe_success{source=\"access\",component_type=\"${component_type}\",job=\"integrations/blackbox/tcp\",project=\"${project}\"})) * 100",
     "legendFormat": "Failed TCP queries"
    }
   ]
  }
 ]
}