apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "osc-vm-power.fullname" . }}-read-machines
  labels:
    {{- include "osc-vm-power.labels" . | nindent 4 }}
rules:
  - apiGroups: ["cluster.x-k8s.io"]
    resources: ["machines"]
    verbs: ["get", "list"]
  {{- if .Values.osc.perTenantCredentials }}
  - apiGroups: ["cluster.x-k8s.io"]
    resources: ["clusters"]
    verbs: ["get"]
  - apiGroups: ["infrastructure.cluster.x-k8s.io"]
    resources: ["oscclusters"]
    verbs: ["get"]
  {{- end }}
