{{- if .Values.osc.perTenantCredentials }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "osc-vm-power.fullname" . }}-read-tenant-secrets
  namespace: {{ .Values.osc.clustersNamespace }}
  labels:
    {{- include "osc-vm-power.labels" . | nindent 4 }}
rules:
  # Secrets <tenant>-tenant référencés par OscCluster.spec.credentials.fromSecret
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get"]
{{- end }}
