{{- $repoURL := .Values.source.repoURL }}
{{- range $appName, $appData := .Values.applications }}
  {{- if hasKey $appData "apps" }}
  {{- range $app, $data := $appData.apps }}
  {{- if eq "mgmt-step-01-cluster-api-operator" $app }}
  {{- $enabled := (or (empty $data) (or (not (hasKey $data "enabled")) (eq $data.enabled true))) }}
  {{- if $enabled }}
---
#
# Application configuration for {{ $app }}
#
# name: {{ $appName }}
# namespace: {{ $.Values.namespace }}
# source.repoURL: {{ $repoURL }}
# source.targetRevision: {{ template "argocd-apps.defaultSourceTargetRevision" $ }}
# source.path: {{ template "argocd-apps.defaultSourcePath" $ }}
# destination.name: {{ template "argocd-apps.defaultDestinationName" (dict "data" $data "default" $appData.environment ) }}
#
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  # here is the argocd app name for the cluster
  name: {{ $app }}
  namespace: {{ $.Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: default
    # here is the url of the mgmt capi-cluster
    #   name: in-cluster
    name: {{ template "argocd-apps.defaultDestinationName" (dict "data" $data "default" "in-cluster" ) }}
  source:
    repoURL: {{ $repoURL }}
    targetRevision: {{ template "argocd-apps.defaultSourceTargetRevision" $ }}
    path: {{ template "argocd-apps.defaultSourcePath" $ }}
    plugin:
      name: helmfile-v1.0
      env:
        # here is the cluster name to configure
        - name: ENV_NAME
          value: {{ default $appName $appData.helmfile_env }}
        - name: HELMFILE_FILE
          value: "helmfile.d/mgmt-step-01-cluster-api-operator"
        - name: HELMFILE_MULTI_NAMESPACE
          value: "true"
  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      jsonPointers:
        - /spec/conversion/webhook/clientConfig/caBundle
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - Validate=true
      - RespectIgnoreDifferences=true
#    automated:
#      prune: true
#      selfHeal: true
#      allowEmpty: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
  {{- end }}
  {{- end }}
  {{- end }}
  {{- end }}
{{- end }}
