apiVersion: v1
kind: ConfigMap
metadata:
  name: cbw-config
  namespace: {{ .Release.Namespace }}
data:
  CBW_NGINX_RESOLVER: {{ required "A valid nginx.resolver entry is required!" .Values.nginx.resolver }}
  CBW_WEB_UPSTREAM: web.{{ .Release.Namespace }}.svc.cluster.local
  CBW_KIBANA_UPSTREAM: kibana.{{ .Release.Namespace }}.svc.cluster.local
        {{- if .Values.rails }}
          {{- if .Values.rails.max_threads }}
  rails-max-threads: {{ .Values.rails.max_threads | quote }}
          {{- end }}
          {{- if .Values.rails.env }}
  rails-env: {{ .Values.rails.env }}
  node-env: {{ .Values.rails.env }}
          {{- end }}
          {{- if .Values.rails.web_concurrency }}
  web-concurrency: {{ .Values.rails.web_concurrency | quote }}
          {{- end }}
        {{- end }}
  term: ""
  use_hsts: {{ .Values.nginx.useHSTS | quote }}
  limit_to_api: {{ .Values.nginx.limitToApi | quote }}
  job-worker-url: redis://{{ default "redis" .Values.redis.host }}:{{ default "6379" .Values.redis.port }}/0
  {{- if .Values.database.tls.mode }}
  db_tls_mode: {{ .Values.database.tls.mode | quote }}
  {{- end }}
  {{- if .Values.database.tls.verify }}
  db_tls_verify: {{ .Values.database.tls.verify | quote }}
  {{- end }}
  {{- if .Values.database.external }}
    {{- if .Values.database.tls.secret }}
    {{- /* Case with external database on master/satellite */}}
  db_tls_ca: '/run/secrets/db/{{ .Values.internalCbw.database.tls.rootCaFilename }}'
    {{- else }}
    {{- /* Case with an 'internal' database with a satellite node */}}
  db_tls_ca: '/run/secrets/certs/cbw-root-ca-cert.pem'
    {{- end }}
  {{- else }}
  {{- /* Case with an 'internal' database */}}
  db_tls_ca: '/run/secrets/certs/cbw-root-ca-cert.pem'
  {{- end }}
  {{- if .Values.redis.external }}
    {{- if .Values.redis.tls.secret }}
    {{- /* Case with external redis on master/satellite */}}
  redis_tls_ca: '/run/secrets/redis/{{ .Values.internalCbw.redis.tls.rootCaFilename }}'
    {{- else }}
    {{- /* Case with an 'internal' redis with a satellite node */}}
  redis_tls_ca: '/run/secrets/certs/cbw-root-ca-cert.pem'
    {{- end }}
  {{- else }}
  {{- /* Case with an 'internal' redis */}}
  redis_tls_ca: '/run/secrets/certs/cbw-root-ca-cert.pem'
  {{- end }}
