{{- if .Values.ingress.enabled }}

{{- /* Deprecated bloc. Use .Values.hosts list instead of .Values.host and .Values.tls.
       Remove this later
*/}}
  {{- if .Values.ingress.host }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx
  namespace: {{ $.Release.Namespace | default "default" }}
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    {{- if .Values.ingress.annotations }}
    {{- include "cbw.render" (dict "value" .Values.ingress.annotations "context" $) | nindent 4 }}
    {{- end }}
spec:
  {{- if .Values.ingress.ingressClassName }}
  ingressClassName: {{ .Values.ingress.ingressClassName | quote }}
  {{- end }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - secretName: {{ ternary (printf "%s-tls" .Values.ingress.host) .Values.ingress.tls.secret (empty .Values.ingress.tls.secret) }}
      {{- if .Values.ingress.host }}
      hosts:
      - {{ .Values.ingress.host }}
      {{- end }}
  {{- end }}
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx
            port:
              number: 443
    {{- if .Values.ingress.host }}
    host: {{ .Values.ingress.host }}
    {{- end }}
  {{- else }}
    {{- range $i, $ingress := .Values.ingress.hosts }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ printf "%s-ingress" $ingress.hostname }}
  namespace: {{ $.Release.Namespace | default "default" }}
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    {{- if $ingress.annotations }}
    {{- include "cbw.render" (dict "value" $ingress.annotations "context" $) | nindent 4 }}
    {{- end }}
spec:
  {{- if $ingress.ingressClassName }}
  ingressClassName: {{ $ingress.ingressClassName | quote }}
  {{- end }}
  {{- if $ingress.tls.enabled }}
  tls:
    - secretName: {{ ternary (printf "%s-tls" $ingress.hostname) $ingress.tls.secret (empty $ingress.tls.secret) }}
      hosts:
      - {{ $ingress.hostname }}
  {{- end }}
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx
            port:
              number: 443
    host: {{ $ingress.hostname }}
    {{- end }}
  {{- end }}
{{- end }}