{{- $existingCA := (lookup "v1" "Secret" .Release.Namespace .Values.internalCbw.global.tls.CaSecret) }}
{{- $ca := dict }}

{{- if $existingCA }}
  {{- $caCert := index $existingCA.data "root-ca.crt" }}
  {{- $caKey := index $existingCA.data "root-ca.key" }}
  {{- $ca = buildCustomCert $caCert $caKey }}
{{- else }}
  {{- $ca = genCA "cyberwatch-ca" 1095 }}
{{- end }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.internalCbw.global.tls.CaSecret }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  {{ .Values.internalCbw.global.tls.rootCaFilename }}: {{ $ca.Cert | b64enc  }}
  root-ca.key: {{ $ca.Key | b64enc  }}


{{- /* Deprecated bloc. Use .Values.hosts list instead of .Values.host and .Values.tls.
       Remove this later
*/}}
{{- if .Values.ingress.host }}
  {{- if (and .Values.ingress.enabled .Values.ingress.tls.enabled) }}
    {{- $ingressExisting := (lookup "v1" "Secret" .Release.Namespace (printf "%s-tls" .Values.ingress.host)) }}
    {{- $ingressKey := "" }}
    {{- $ingressCertificate := "" }}
    {{- $ingressSecretType := "kubernetes.io/tls" }}
    {{- if and .Values.ingress.tls.ingressTLSCertificate .Values.ingress.tls.ingressTLSKey }}
      {{- $ingressKey = .Values.ingress.tls.ingressTLSKey }}
      {{- $ingressCertificate = .Values.ingress.tls.ingressTLSCertificate }}
    {{- else }}
      {{- if $ingressExisting }}
        {{- $ingressCertificate = index $ingressExisting.data "tls.crt" }}
        {{- $ingressKey = index $ingressExisting.data "tls.key" }}
        {{- /* Store the type of the secret defined by the user to avoir breaking changes */}}
        {{- $ingressSecretType = $ingressExisting.type }}
      {{- else }}
        {{- $certGenerated := genSignedCert .Values.ingress.host nil (list .Values.ingress.host) 1095 $ca }}
        {{- $ingressCertificate = $certGenerated.Cert | b64enc }}
        {{- $ingressKey = $certGenerated.Key | b64enc }}
      {{- end }}
    {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-tls" .Values.ingress.host }}
  namespace: {{ .Release.Namespace }}
type: {{ $ingressSecretType }}
data:
  tls.crt: {{ $ingressCertificate }}
  tls.key: {{ $ingressKey }}
  {{- end }}
{{- else }}
{{- /* Disable the parsing of .Values.hosts list if .Values.host is still used
       to avoid conflict between configurations.
*/}}
  {{- $namespace := .Release.Namespace }} {{- /* Save namespace here to use it in the range because range changes the context. */}}
  {{- range $i, $ingress := .Values.ingress.hosts }}
    {{- if (and $ingress.tls.enabled (not $ingress.tls.secret)) }}
    {{- /* Generate a secret only if tls should be used and if the user does not provide its own tls secret. */}}
      {{- $ingressExisting := (lookup "v1" "Secret" $namespace (printf "%s-tls" $ingress.hostname)) }}
      {{- $ingressKey := "" }}
      {{- $ingressCertificate := "" }}
      {{- $ingressSecretType := "kubernetes.io/tls" }}
      {{- if and $ingress.tls.ingressTLSCertificate $ingress.tls.ingressTLSKey }}
        {{- $ingressKey = $ingress.tls.ingressTLSKey }}
        {{- $ingressCertificate = $ingress.tls.ingressTLSCertificate }}
      {{- else }}
        {{- if $ingressExisting }}
          {{- $ingressCertificate = index $ingressExisting.data "tls.crt" }}
          {{- $ingressKey = index $ingressExisting.data "tls.key" }}
          {{- /* Store the type of the secret defined by the user to avoir breaking changes */}}
          {{- $ingressSecretType = $ingressExisting.type }}
        {{- else }}
          {{- $certGenerated := genSignedCert $ingress.hostname nil (list $ingress.hostname) 1095 $ca }}
          {{- $ingressCertificate = $certGenerated.Cert | b64enc }}
          {{- $ingressKey = $certGenerated.Key | b64enc }}
        {{- end }}
      {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-tls" $ingress.hostname }}
  namespace: {{ $namespace }}
type: {{ $ingressSecretType }}
data:
  tls.crt: {{ $ingressCertificate }}
  tls.key: {{ $ingressKey }}

    {{- end }}
  {{- end }}
{{- end }}


{{- if (not .Values.database.external) }}
  {{- $databaseExisting := (lookup "v1" "Secret" .Release.Namespace .Values.internalCbw.database.tls.CertSecret) }}
  {{- $databaseCertificate := "" }}
  {{- $databaseKey := "" }}
  {{- if $databaseExisting }}
    {{- $databaseCertificate = index $databaseExisting.data "tls.crt" }}
    {{- $databaseKey = index $databaseExisting.data "tls.key" }}
  {{- else }}
    {{- $dbCert := genSignedCert .Values.database.host nil (list .Values.database.host) 1095 $ca }}
    {{- $databaseCertificate = $dbCert.Cert | b64enc }}
    {{- $databaseKey = $dbCert.Key | b64enc }}
  {{- end }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.internalCbw.database.tls.CertSecret }}
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/tls
data:
  tls.crt: {{ $databaseCertificate }}
  tls.key: {{ $databaseKey }}
{{- end }}


{{- if (not .Values.redis.external) }}
  {{- $redisExisting := (lookup "v1" "Secret" .Release.Namespace .Values.internalCbw.redis.tls.CertSecret ) }}
  {{- $redisCertificate := "" }}
  {{- $redisKey := "" }}
  {{- if $redisExisting }}
    {{- $redisCertificate = index $redisExisting.data "tls.crt" }}
    {{- $redisKey = index $redisExisting.data "tls.key" }}
  {{- else }}
    {{- $redisCert := genSignedCert .Values.redis.host nil (list .Values.redis.host) 1095 $ca }}
    {{- $redisCertificate = $redisCert.Cert | b64enc }}
    {{- $redisKey = $redisCert.Key | b64enc }}
  {{- end }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.internalCbw.redis.tls.CertSecret }}
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/tls
data:
  tls.crt: {{ $redisCertificate }}
  tls.key: {{ $redisKey }}
{{- end }}
