apiVersion: v1
kind: Secret
metadata:
  name: cbw-secrets
  namespace: {{ .Release.Namespace }}
stringData:
  mysql-hostname: {{ .Values.database.hostname | default .Values.database.host }}
  mysql-database: {{ .Values.database.name }}
  mysql-user: {{ .Values.database.user }}
  mysql-port: {{ .Values.database.port | quote }}
{{- if and (not ((.Values.database.passwordSecret | default dict).name | default false)) .Values.database.password }}
  mysql-password: {{ .Values.database.password }}
{{- end }}
{{- if and (not ((.Values.database.rootPasswordSecret | default dict).name | default false)) .Values.database.root_password }}
  mysql-root-password: {{ .Values.database.root_password }}
{{- end }}
{{- if and (not ((.Values.redis.passwordSecret | default dict).name | default false)) .Values.redis.password }}
  redis-password: {{ .Values.redis.password }}
{{- end }}
{{- if and (not ((.Values.key.baseSecret | default dict).name | default false)) .Values.key.base }}
  secret-key-base: {{ .Values.key.base }}
{{- end }}
{{- if and (not ((.Values.key.credentialSecret | default dict).name | default false)) .Values.key.credential }}
  secret-key-credential: {{ .Values.key.credential }}
{{- end }}
{{- if and (not ((.Values.webScanner.webScannerApiKeySecret | default dict).name | default false)) .Values.webScanner.web_scanner_api_key }}
  web-scanner-api-key: {{ .Values.webScanner.web_scanner_api_key }}
{{- end }}
{{- if and (not ((.Values.containerScanner.containerScannerApiKeySecret | default dict).name | default false)) .Values.containerScanner.container_scanner_api_key }}
  container-scanner-api-key: {{ .Values.containerScanner.container_scanner_api_key }}
{{- end }}

{{- if and .Values.global.pki.root_ca_certificate (not (lookup "v1" "Secret" .Release.Namespace .Values.global.pki.root_ca )) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.pki.root_ca }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  cbw-root-ca-cert.pem: {{ .Values.global.pki.root_ca_certificate }}
{{- end }}

{{- if .Values.database.tls.databaseRootCa }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.internalCbw.database.tls.rootCaHelmSecret }}
  namespace: {{ .Release.Namespace }}
type: generic
data:
  {{ .Values.internalCbw.database.tls.rootCaFilename }}: {{ .Values.database.tls.databaseRootCa }}
{{- end }}

{{- if .Values.redis.tls.redisRootCa }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.internalCbw.redis.tls.rootCaHelmSecret }}
  namespace: {{ .Release.Namespace }}
type: generic
data:
  {{ .Values.internalCbw.redis.tls.rootCaFilename }}: {{ .Values.redis.tls.redisRootCa }}
{{- end }}