# Config example:
# secrets:
#   secret_tls:
#     name: 'secret-tls'
#     type: kubernetes.io/tls
#     data:
#       tls.crt: |
#         000000000000000000000000000
#       tls.key: |
#         111111111111111111111111111
#   secret_opaque:
#     name: 'secret-opaque'
#     type: Opaque
#     namespace: my-namespace
#     data:
#       USER_NAME: batman
#       PASSWORD: batman
secrets: {}
